### ISSUE TITLE
Language Files

### ISSUE THREAD

**Issue by Lukin-zz** [CheeseSucker/silverstripe-guestbook#1]
Hi,

I set up a new language file for german translation, but it does not load it.
filename is de.yml, does it wrok for anybody? do you want to integrate it into your project?

kind regrads

**Comment by CheeseSucker** [comment]
Could you send me the language file so I can test it? If I can get it to work I will gladly add it to the project :)

I created a fake german translation on my computer and it worked without issues.

Here are a few things you could check:
- Filename: `de.yml`
- First line in file should be same as filename: `de:`
- Cache must be reloaded to see changes, so add `?flush=1` to your url after you update the translation. (Example: http://example.org/guestbook?flush=1)
- Check that you have used the correct locale. I have `i18n::set_locale('de_DE');` in my `_config.php`.

**Comment by Lukin-zz** [comment]
hi,
I got it running. I'm not sure.
I think it was because I had several languagefiles in several modules and one in mysite,... I merged them all an now it s working,...

![de](https://cloud.githubusercontent.com/assets/480172/8160664/ca26391a-1371-11e5-88c6-62df8257acb7.jpg)
rename filetype to yml... ;)

**Comment by CheeseSucker** [comment]
Thank you. I will add the translation later this evening =)

**Comment by CheeseSucker** [comment]
I think I found the problem you had. SilverStripe apparently expects translation files to use UTF-8 encoding. Most text editors can be configured to save files in this encoding.

**Comment by Lukin-zz** [comment]
Ah ok,.. thanks,... I use notepad++, i'll check that out...
